//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkGravestock.SportTracks.PlugIns.PoolMatePro.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkGravestock.SportTracks.PlugIns.PoolMatePro.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Pool Length: {0}.
		/// </summary>
		internal static string ActivityDescription {
			get {
				return ResourceManager.GetString("ActivityDescription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Invalid User Number: Please enter an integer between 1 and 3.
		/// </summary>
		internal static string DeviceConfigurationDialog_Error_InvalidUserNumber {
			get {
				return ResourceManager.GetString("DeviceConfigurationDialog_Error_InvalidUserNumber", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Select the directory that contains the files imported using the PoolMate Link..
		/// </summary>
		internal static string DeviceConfigurationDialog_folderBrowserDialog_Description {
			get {
				return ResourceManager.GetString("DeviceConfigurationDialog_folderBrowserDialog_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Directory ....
		/// </summary>
		internal static string DeviceConfigurationDlg_btnDirectoryChooser_Text {
			get {
				return ResourceManager.GetString("DeviceConfigurationDlg_btnDirectoryChooser_Text", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Only Import New Sessions..
		/// </summary>
		internal static string DeviceConfigurationDlg_chkImportOnlyNew_Text {
			get {
				return ResourceManager.GetString("DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Pool Mate Directory:.
		/// </summary>
		internal static string DeviceConfigurationDlg_labelImportDirectory_Text {
			get {
				return ResourceManager.GetString("DeviceConfigurationDlg_labelImportDirectory_Text", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to User Number.
		/// </summary>
		internal static string DeviceConfigurationDlg_labelUserNumber_Text {
			get {
				return ResourceManager.GetString("DeviceConfigurationDlg_labelUserNumber_Text", resourceCulture);
			}
		}
		
		internal static System.Drawing.Bitmap Image_48_PoolMatePro {
			get {
				object obj = ResourceManager.GetObject("Image_48_PoolMatePro", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Import Complete.
		/// </summary>
		internal static string ImportComplete {
			get {
				return ResourceManager.GetString("ImportComplete", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Import Starting..
		/// </summary>
		internal static string ImportStarting {
			get {
				return ResourceManager.GetString("ImportStarting", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Unable to find any files to import in directory..
		/// </summary>
		internal static string InvalidImportDirectory {
			get {
				return ResourceManager.GetString("InvalidImportDirectory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Efficiency: {0} Strokes: {1}.
		/// </summary>
		internal static string LapDescription {
			get {
				return ResourceManager.GetString("LapDescription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Metres.
		/// </summary>
		internal static string LengthUnitMetres {
			get {
				return ResourceManager.GetString("LengthUnitMetres", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Yards.
		/// </summary>
		internal static string LengthUnitYards {
			get {
				return ResourceManager.GetString("LengthUnitYards", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No files found to import..
		/// </summary>
		internal static string NothingToImport {
			get {
				return ResourceManager.GetString("NothingToImport", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Swimming.
		/// </summary>
		internal static string SwimmingActivityName {
			get {
				return ResourceManager.GetString("SwimmingActivityName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;Unknown&gt;.
		/// </summary>
		internal static string UnknownValue {
			get {
				return ResourceManager.GetString("UnknownValue", resourceCulture);
			}
		}
	}
}
